### ISSUE TITLE
MediaDrop installation notes bug

### ISSUE THREAD

**Issue by rbu** [mediadrop/mediadrop#179]
[Installation notes](http://mediadrop.net/docs/install/index.html) say

```
paster make-config MediaCore deployment.ini
```

when they should say

```
paster make-config MediaDrop deployment.ini
```

Running the former command yields:

```
Must install MediaCore
Searching for MediaCore
Reading https://pypi.python.org/simple/MediaCore/
Couldn't find index page for 'MediaCore' (maybe misspelled?)
```

**Comment by Leryan** [comment]
Well well well, with release 1.10.3, using MediaDrop instead of MediaCore doesn't work. I used MediaCore and all was fine. How strange it is?

**Comment by Snarkly** [comment]
There needs to be more coders working on this project. MediaDrop would be a good alternative to Youtube since Youtube does nothing but censor now.
