### ISSUE TITLE
Documentaion Error (minor)

### ISSUE THREAD

**Issue by net127** [mediadrop/mediadrop#182]
On http://mediadrop.net/docs/install/index.html

Step 3: create deployment.ini
Step 4: Copy the data folder from your MediaDrop source code next to the production.ini file.

What "production.ini" file? Assuming "deployment.ini"

**Comment by FelixSchwarz** [comment]
of course you are right. Fixed in 5f12b48157b932228de3a636409c3c881a4924bf
