### ISSUE TITLE
provide a vagrant file

### ISSUE THREAD

**Issue by allan-simon** [mediadrop/mediadrop#196]
Hello, would you be interested in a vagrantfile in order for people to create easily a virtualmachine ?

**Comment by FelixSchwarz** [comment]
yes, sure. Would you be willing to maintain this file?

**Comment by allan-simon** [comment]
I think I can

**Comment by brainysmurf** [comment]
+1

**Comment by allan-simon** [comment]
I'm very sorry but actually I thought i would have been able to work on mediadrop as part of a project, but we're considering an other solution now. 

on a side note a guy has already made a vagrant file here https://github.com/jcf/vagrant-mediadrop you may want to contact him to see if he's interested in getting it merged here ?

**Comment by FelixSchwarz** [comment]
I'd be interested in merging a vagrant file as long as someone is there to maintain it. I sent an email to James. In the meantime I'm closing this issue as it's not clear if someone is working on that. Feel free to reopen though.
