### ISSUE TITLE
Tutorial videos are missing (need symlink)

### ISSUE THREAD

**Issue by RichardNeill** [mediadrop/mediadrop#202]
I just installed mediadrop from git today. The first thing it offers me is a video tutorial of the workflow.
When I click it to play, I get the error:

"The video could not be loaded, either because the server or network failed or because the format is not supported: http://static.mediadrop.net/files/videos/tutorial-workflow-in-mediadrop.mp4"

This is because mediadrop.net has the wrong filenames, it still refers to mediacore. 
http://static.mediadrop.net/files/videos/
￼	tutorial-add-video-in-mediacore.mp4	14-Oct-2014 17:49	3.8M	 
￼	tutorial-create-podcast-in-mediacore.mp4	14-Oct-2014 17:49	3.4M	 
￼	tutorial-workflow-in-mediacore.mp4	14-Oct-2014 17:49	5.9M	 
I think that some symlinks are needed on the mediadrop.net server for all 3 of these.

Also, this isn't a very helpful error message - it should distinguish "file-not-found" from "can't-play-this-format".

**Comment by FelixSchwarz** [comment]
Thank you very much for reporting this. It's fixed now.
