### ISSUE TITLE
BeautifulSoup == 3.0.7a is not available via pypi

### ISSUE THREAD

**Issue by huiyiqun** [mediadrop/mediadrop#209]
As I can see from [here](https://pypi.python.org/simple/beautifulsoup/), 3.0.7a has been not available from pypi, and `pypi install BeautifulSoup == 3.0.7a` results in failure.

But this version of BeautifulSoup is depend by mediadrop. So how can I install mediadrop?

**Comment by rbu** [comment]
Did you try installing via pip? You should download a copy and run "python setup.py develop" as described on http://mediadrop.net/docs/install/index.html#step-1-setup-a-python-virtual-environment

Then you'd get the file at http://static.mediadrop.net/dependencies/dev/BeautifulSoup/

Nevertheless, we could probably upgrade the BS version required or have a look at https://github.com/mediadrop/mediadrop/pull/205

**Comment by FelixSchwarz** [comment]
At least in the current git this is fixed as we now use bleach.
