### ISSUE TITLE
Do you have a demo platform?

### ISSUE THREAD

**Issue by mseibert** [mediadrop/mediadrop#212]
I am unable to install your software. Is there a public demo account that I could use?

**Comment by rbu** [comment]
There's a demo instance at http://demo.mediadrop.net/ however you can only see the user view.

**Comment by mseibert** [comment]
Hi Robert,

I assume that it is on purpose, that no accounts to upload media is available. Any way to get access nevertheless? Can I send you my passport ID to make anyone feel, that I am not going to mess around with the platform?

Next problem: 
None of the videos is playing. See screenshot:



Would love to really test the software? Asking our admins is the only / best way to go?

Best regards
Martin Seibert

//SEIBERT/MEDIA, T. +1-619-798-6420
http://seibert.biz/martinseibert


Atlassian Confluence based Intranet for your company: http://seibert.biz/linchpinintranet

**Comment by rbu** [comment]
Unfortunately, your attachment does not show up in the GitHub issue comment. But you are correct, the mp4 files are not loading. I do not have access to the demo server, so I can neither repair the issue nor allow you upload access -- it's not even a question of trust :-)

To run your own local instance, I suggest you follow the steps at http://mediadrop.net/docs/install/index.html and ask your admins or the community for help (preferably on the forum, as this issue tracker is for code-level issues).

**Comment by rbu** [comment]
mp4 files are loading again, so this issue can be closed
