### ISSUE TITLE
aniso8601 and others is missing from dependencies mirror

### ISSUE THREAD

**Issue by rbu** [mediadrop/mediadrop#220]
Please add the zip. Current master is not installable (and I wanted to get it onto with travis-ci).

**Comment by FelixSchwarz** [comment]
done

**Comment by rbu** [comment]
Can't find it at http://static.mediadrop.net/dependencies/dev/ yet

**Comment by FelixSchwarz** [comment]
bad, bad Felix: I pushed the wrong repo back then. Fixed now: http://static.mediadrop.net/dependencies/dev/aniso8601/

**Comment by rbu** [comment]
Sorry to bug all the time, but WebTest is also missing some more Python 2.6-only dependencies.

From https://github.com/Pylons/webtest/blob/master/setup.py
```
if sys.version_info[0:2] < (2, 7):
    install_requires.append('ordereddict')
    tests_require.append('unittest2')
```

After pushing the zip files you can simply re-trigger the build with the "restart" button on https://travis-ci.org/mediadrop/mediadrop/jobs/97962026 to see if there's even more.

**Comment by FelixSchwarz** [comment]
fixed now. Build is failing because of SkipTest :-)

**Comment by rbu** [comment]
Finally a real test failure ;-)  see #221 for that
