### ISSUE TITLE
Installation setup error

### ISSUE THREAD

**Issue by rajkotraja** [mediadrop/mediadrop#227]
i am trying this on Ubuntu system.
i am getting Tosca widget requirement error, if i installed version 0.9.9, it asks for 0.9.12 of tosca widget and if i install 0.9.12, it asks for 0.9.9

This occurs when i am trying to setup tables in database by:
   paster setup-app deployment.ini

PLs let me know the solution.

**Comment by rbu** [comment]
Hello rajkotraja, there's an installation step by step manual over at http://www.mediadrop.net/docs/install/debian-ubuntu.html

If you have any errors, please report the exact commands you ran and copy error messages to the issue.

**Comment by rbu** [comment]
I'm closing this due to lack of response. If you can give a reproducer, please reopen.
