### ISSUE TITLE
Update mediadrop.net site

### ISSUE THREAD

**Issue by mvdkleijn** [mediadrop/mediadrop#228]
I just found MediaDrop and it looks awesome, works like a charm so far. However, the website (and possible docs) doesn't seem to have been updated since 2013....

There also hasn't been an official release since 2013...

Does this mean an awesome project is dying out or did you simply not update & release? Please update the site, docs and release the software.

**Comment by mvdkleijn** [comment]
*bump*?

**Comment by brainysmurf** [comment]
I am also concerned about the lack of activity. I emailed Felix privately, no reply?

**Comment by rbu** [comment]
The code is used in production, so it's definitely not dead. However, there's little work done at the core, I agree. Contributions are welcome (feel free to pick an issue, have a look and create a pull request or start a discussion on the tracker), as are contributors who want to maintain it.

Documentation/site/release management is currently with Felix (which is fine with me), so it's more of a bottleneck than the code. We could really get a bugfix release out.

**Comment by kallies** [comment]
mediadrop.net tells "This Domain Name Has Expired". Has it moved? Can we support you somehow bringing it back online?

**Comment by FelixSchwarz** [comment]
I'm already in contact with MediaCore Inc. to resolve the situation.

Background: MediaCore Inc. registered the domain name and paid gratiously for
it but for some reason they decided to not renew the domain this time (without
telling me about their plans). I hope I can still move the domain to under my
own account. I'll keep you updated.

**Comment by FelixSchwarz** [comment]
Looks like this might take more time: MediaCore Inc. was acquired by Workday last year and now they are big-ish company with the need to "clarify policies on domain transfer" etc. The domain is now within the reactivation period and US registrars found a new cash source by running "auctions" for expired domains.

Anyway I just registered "mediadrop.video" and this domain is now under my own account so we never have to deal with "expired" domains anymore in the future. Will update all references in the next days.

**Comment by FelixSchwarz** [comment]
Another update: Surprisingly everything worked out and I now control mediadrop.net. However as I registered mediadrop.video I intend to use .video as the primary domain in the future.
