### ISSUE TITLE
Linux software manager

### ISSUE THREAD

**Issue by Snarkly** [mediadrop/mediadrop#229]
This project needs an easy way to install it. It needs to be added to the linux software manager.

**Comment by archenroot** [comment]
To me more important is the future of this awesome project as it looks quiet ....

Packaging is another story of course, so:
+1

**Comment by FelixSchwarz** [comment]
you are right: easier installation would be nice. Help is welcome.

Right now we need to fix even more pressing issues so I'm closing a lot of old bug reports. I'll keep you request in mind though.
