### ISSUE TITLE
Download link broken on the website

### ISSUE THREAD

**Issue by isAAAc** [mediadrop/mediadrop#236]
hi all, 
https://mediadrop.video/download gives a 404 error

**Comment by BlakeRusso** [comment]
I second that, it isn't just you. I emailed the owner of the site last night but no response yet.

I tried github clone as well, but it appears to also download from the site when getting dependencies ( I think it is might be related, might be firewall issues though).

I also opened a thread (no response yet) on the MediaDrop Community Forum at https://mediadrop.video/community/topic/mediadrop-404-errors-with-downloads-any-issues

**Comment by FelixSchwarz** [comment]
Yeah, sorry. I misconfigured the server and noticed the problem too late myself. Did not have
the time to fix it until now (should be fine now).

**Comment by BlakeRusso** [comment]
Appreciate it Felix, I actually did the same when trying to configure Apache is why I am trying to download the software again haha! Looks good now, appreciate it man!
