### ISSUE TITLE
Traboule to Intsall v0.10-stabel

### ISSUE THREAD

**Issue by http403** [mediadrop/mediadrop#242]
I'm trying to follow https://mediadrop.video/docs/install/index.html to install a stable version of mediadrop on CentOS 7 in VirtualBox but I encounter multiple problems before and during `python setup.py develop`.

- allow_hosts in `setup.cfg` is out dataed, fail to fetch dependencies
  #241 

- BeautifulSoup is outdated
  there is no version 3.0.7a on PiPy, only 3.2.1 but `setup.py` need that specific version

Mainly is this two problems, there are some warning during the setup and I will save [the output at Gist](https://gist.github.com/http403/f61f87900de11472ebc2574f4d0cc206).

**Comment by FelixSchwarz** [comment]
Please install the latest git version. I know this is a bit annoying (also given the fact that this is still featured prominently on the web page) but the dependencies for 0.10 are out of date (as you noticed).

Please note that the setup process should fetch all of its dependencies from https://static.mediadrop.video/dependencies/ which provides tested versions.
