### ISSUE TITLE
Admin User Accidentally deleted.  Ran SQL and Python Shell script on http://mediadrop.video, doesn't work.

### ISSUE THREAD

**Issue by jd4rider** [mediadrop/mediadrop#244]
I ran the following to re-establish my admin user and it still won't login as admin/admin:

https://mediadrop.video/community/topic/accidently-deleted-admin-user

Running a ubnuntu 16.04 server.

Thanks,

Joanthan

**Comment by FelixSchwarz** [comment]
Probably the easiest way is just to use SQL.

Check how thoroughly your admin user is deleted:

    MariaDB [mediadrop]> select * from users where user_name="admin";
    # likely output: Empty set (0.00 sec)

    MariaDB [mediadrop]> select * from users_groups;
    # likely output: Empty set (0.00 sec)

    MariaDB [mediadrop]> select * from groups;
    +----------+---------------+-----------------------------+---------------------+
    | group_id | group_name    | display_name                | created             |
    +----------+---------------+-----------------------------+---------------------+
    |        1 | admins        | Admins                      |    . ..             |
    ...

Assuming you lost the "admin" user and its group affiliation but not the admin group you can do this:

    MariaDB [mediadrop]> insert into users (user_name, email_address, display_name, password) VALUES ("admin", "admin@site.example", "Admin", "6590658e2e1c434c2856eafa9298ef63dcd8fc8527dbd7d8225f39133b5a0a09ad1f45a8a0b7c68f");

    # get the user id of the newly created admin

    MariaDB [mediadrop]> insert into users_groups (user_id, group_id) VALUES (XXX, 1);

Afterwards you should have a new "admin" user with password "admin".
